model_names:
  - "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract"
  - "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
  - "FacebookAI/roberta-base"
  - "dmis-lab/biobert-v1.1"
  - "google-bert/bert-base-uncased"
fold: 0
run: 0
loss_type: "BCE"
with_title: True
with_keywords: False
nb_optional_negs: 100
